name: Run install dependencies script
on:
  push:
    paths:
      - source/_static/install_dependencies.sh
jobs:
  install-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: source/_static/install_dependencies.sh

  install-fedora:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: cp ci/fedora.vagrant Vagrantfile
      - run: vagrant up
